spring.application.name=SpringSecurityAuthDemo
server.port=2026

spring.datasource.url=jdbc:mysql://localhost:3306/sec2
spring.datasource.username=root
spring.datasource.password=#Sudheer@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true